name: Codequality

on: [push, pull_request]

jobs:
  codequality:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.6.x]

    steps:
    - uses: actions/checkout@master
    - name: Codequality stage with Node.js matrix version - ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run codequality
      env:
        CI: true
